services:
  - type: web
    name: ezerd
    env: node
    buildCommand: npm install --production=false && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production 